ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from products import urls as products_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(products_urls, namespace='products'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from .views import GetProducts, GetProduct

app_name = 'products'
urlpatterns = [
    path('', GetProducts.as_view(), name='list'),
    path('<int:id>', GetProduct, name='detail')
]

products/models.py
from django.db import models
from django.urls import reverse

CATEGORIES = (
    ('electronics', 'Electrónicos'),
    ('cameras', 'Cámaras'),
    ('computers', 'Computadoras'),
    ('cellphones', 'Celulares'),
    ('accesories', 'Accesorios')
)

# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=140)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    desc = models.TextField(blank=True, null=True)
    image = models.ImageField(upload_to='images/products/', blank=True, null=True)
    category = models.CharField(max_length=20, choices=CATEGORIES)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.name} - ${self.price}'

    def get_absolute_url(self):
        return reverse('products:detail', args=[self.id])

products/views.py
from django.shortcuts import render
from django import views
from django.db.models import Q
from .models import Product

class GetProducts(views.View):
    def get(self, request):
        products = Product.objects.filter(is_active=True)
        search = request.GET['search'] if request.GET.get('search') else None
        category = request.GET['category'] if request.GET.get('category') else None
        if search:
            products = products.filter(Q(name__icontains=search))
        if category:
            products = products.filter(category=category)
        counter = len(products)
        template_name = 'products/list.html'
        context = {
            'products': products,
            'counter': counter,
            'search': search,
            'category': category
        }
        return render(request, template_name, context)

def GetProduct(request, id):
    product = Product.objects.get(pk=id, is_active=True)
    template_name = 'products/detail.html'
    context = {
        'product': product
    }
    return render(request, template_name, context)

products/templates/products/detail.html
{% extends 'index.html' %}

{% block content %}
    <img
        src="
            {% if product.image %}
                {{ product.image.url }}
            {% else %}
                https://www.amerikickkansas.com/wp-content/uploads/2017/04/default-image.jpg
            {% endif %}
        "
        alt="Product Image" width="200" height="200" style="margin-right: 20px;"
    >
    <h1>{{ product.name }}</h1>
    <h2>${{ product.price }}</h2>
    <p>Categoría: <b>{{ product.category }}</b></p>
    <p>Descripción: {% if product.desc %}{{ product.desc }}{% else %}Sin descripción{% endif %}</p>
{% endblock content %}

products/templates/products/list.html
{% extends 'index.html' %}

{% block content %}
    <h2>¡Productos disponbiles para ti!</h2>
    <ul>
    {% if counter > 0 %}
        {% for product in products %}
            <li style="list-style-type: none; margin: 30px 0; display: flex; align-items:center;">
                <img
                    src="
                        {% if product.image %}
                            {{ product.image.url }}
                        {% else %}
                            https://www.amerikickkansas.com/wp-content/uploads/2017/04/default-image.jpg
                        {% endif %}
                    "
                    alt="Product Image" width="50" height="50" style="margin-right: 20px;"
                >
                <a href="{{ product.get_absolute_url }}">
                    <span>{{product.name}} - $<b>{{product.price}}</b></span>
                </a>
            </li>
        {% endfor %}
        <h3>Total: {{ counter }}</h3>
    {%else%}
        <h3>No hay productos, intenta con otro nombre</h3>
    {% endif %}
    </ul>
{% endblock content %}

templates/index.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django micro E-Commerce</title>
</head>
<body>
    <header>
        <ul>
            <a href="{% url 'products:list' %}"><li>Inicio</li></a>
        </ul>
        <h1>Bienvenidos al E-Commerce hecho en Django en tiempo récord</h1>
        <div>
            <form action="{% url 'products:list' %}">
                <input type="text" name="search" id="search" placeholder="Busca productos..."
                    value="{% if search %}{{ search }}{% endif %}"
                >
                <select name="category" id="category">
                    <option value="">Elige una categoría</option>
                    <option value="electronics">Electrónicos</option>
                    <option value="cameras">Cámaras</option>
                    <option value="computers">Computadoras</option>
                    <option value="cellphones">Celulares</option>
                    <option value="accesories">Accesorios</option>
                </select>
                <input type="submit" value="Buscar!">
            </form>
            <a href="{% url 'products:list' %}"><button>Reiniciar filtros</button></a>
        </div>
    </header>
    <main>
        <div>
            {% block content %}
            {% endblock content %}
        </div>
    </main>
    <footer>
        <p>Actosoft 2020</p>
    </footer>
</body>
</html>